apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-object-store
  namespace: rook-ceph
spec:
  gateway:
    port: 80
    instances: 2
  metadataPool:
    replicated:
      size: 3
  dataPool:
    replicated:
      size: 3
  preservePoolsOnDelete: true
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: loki-user
  namespace: rook-ceph
spec:
  store: ceph-object-store
  displayName: "loki"
