apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.3
    helm:
      values: |
        prometheus:
          enabled: true
        
        loki:
          enabled: true
        
          config:
            auth_enabled: false
        
            storage_config:
              aws:
                s3: http://$(S3_ACCESS_KEY):$(S3_SECRET_KEY)@rook-ceph-rgw-ceph-object-store.rook-ceph.svc:80/loki
                s3forcepathstyle: true
                insecure: true
        
            schema_config:
              configs:
                - from: 2026-01-21
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
          minio:
            enabled: false
        
          persistence:
            enabled: false
        
        promtail:
          enabled: true
        
        grafana:
          enabled: true
          adminPassword: 12345678

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
